FROM python:3.10-slim

# Copy the files over
COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Fix the time issue of connection
RUN apt-get install ntp

CMD ["python", "sw-queue.py"]
